enum ActionTypes {
    AUTH_LOADING = "AUTH_LOADING",
    AUTH_AUTHENTICATION = "AUTH_AUTHENTICATION",
    AUTH_VALIDATE = "AUTH_VALIDATE",
    AUTH_SET_USER = "AUTH_SET_USER",
    AUTH_VALIDATE_USERNAME = "AUTH_VALIDATE_USERNAME",
    AUTH_VALIDATE_EMAIL = "AUTH_VALIDATE_EMAIL",
    AUTH_FAIL = "AUTH_FAIL",
    AUTH_LOGOUT = "AUTH_LOGOUT",

    FOOD_LOADING = "FOOD_LOADING",
    FOOD_SET = "FOOD_SET",
    FOOD_SET_PAGEABLE = "FOOD_SET_PAGEABLE",

    DRAWER_INITIALIZE = "DRAWER_INITIALIZE",
    DRAWER_LOADING = "DRAWER_LOADING",
    DRAWER_SET = "DRAWER_SET",
    DRAWER_ADD = "DRAWER_ADD",
    DRAWER_UPDATE = "DRAWER_UPDATE",
    DRAWER_REMOVE = "DRAWER_REMOVE",

    CATEGORY_INITIALIZE = "CATEGORY_INITIALIZE",
    CATEGORY_LOADING = "CATEGORY_LOADING",
    CATEGORY_SET = "CATEGORY_SET",
    CATEGORY_SINGLE = "CATEGORY_SINGLE",
    CATEGORY_SET_PAGEABLE = "CATEGORY_SET_PAGEABLE",

    SEARCH_LOADING = "SEARCH_LOADING",
    SEARCH_RESULTED = "SEARCH_RESULTED",
    SEARCH_SET_TEXT = "SEARCH_SET_TEXT",
    SEARCH_SET_PAGE = "SEARCH_SET_PAGE",
    SEARCH_SET_TOTAL = "SEARCH_SET_TOTAL",
    SEARCH_SET_CATEGORY = "SEARCH_SET_CATEGORY",
    SEARCH_SET_RESULTS = "SEARCH_SET_RESULTS",
    SEARCH_RESULT_CLEAR = "SEARCH_RESULT_CLEAR",
};
export default ActionTypes;